line-length = 88
exclude = [".git", "__pycache__", ".venv", "env", "venv", ".pytest_cache", "data", "archive", "output", "notebooks"]
target-version = "py312"

[lint]
ignore = ["E203"]
select = ["E", "F", "W", "C90"]